// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyxxmdostbrlkavuqipk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5eHhtZG9zdGJybGthdnVxaXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODYwMDgsImV4cCI6MjA3MzY2MjAwOH0.HG9FfaKTbu4P4ZOtU5aLbhq_0BrrgBlANCMg34fA4uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});